# Generated by Django 4.2.16 on 2025-07-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=20, null=True)),
                ("lastname", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="profile/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
