# Generated by Django 4.2.16 on 2025-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
